# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Vivado/vivadoworkspace/FinalExperiment/FinalExperiment.cache/wt [current_project]
set_property parent.project_path F:/Vivado/vivadoworkspace/FinalExperiment/FinalExperiment.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib F:/Vivado/vivadoworkspace/FinalExperiment/FinalExperiment.srcs/sources_1/new/Main.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Vivado/vivadoworkspace/FinalExperiment/FinalExperiment.srcs/constrs_1/new/MyXDC.xdc
set_property used_in_implementation false [get_files F:/Vivado/vivadoworkspace/FinalExperiment/FinalExperiment.srcs/constrs_1/new/MyXDC.xdc]


synth_design -top Main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Main.dcp

catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
